from itertools import combinations, product

popcount = int.bit_count if hasattr(int, "bit_count") else (lambda x: bin(x).count("1"))


def bits(x):
    """Yield the indices of the set bits of x."""
    while x:
        low = x & -x
        yield low.bit_length() - 1
        x ^= low


# --------------------------------------------------------------------------
# 0. Convert the (V, node_attribute_set, R) input into bitmasks
# --------------------------------------------------------------------------
class Context:
    def __init__(self, V, node_attribute_set, R):
        self.nodes = list(V)
        self.n = len(self.nodes)
        idx = {v: i for i, v in enumerate(self.nodes)}
        self.idx = idx
        self.full = (1 << self.n) - 1
        self.attributes = [a for a in dict.fromkeys(node_attribute_set) if a not in idx]

        # N[i]  = closed neighbourhood of node i (row of the modified adjacency matrix)
        # adj[i] = open neighbourhood
        self.adj = [0] * self.n
        attr_ix = {a: k for k, a in enumerate(self.attributes)}
        self.attr_mask = [0] * len(self.attributes)      # nodes carrying attribute a
        for a, b in R:
            if a in idx and b in idx:
                if a != b:
                    self.adj[idx[a]] |= 1 << idx[b]
                    self.adj[idx[b]] |= 1 << idx[a]
            elif a in idx and b in attr_ix:
                self.attr_mask[attr_ix[b]] |= 1 << idx[a]
        self.N = [self.adj[i] | (1 << i) for i in range(self.n)]

        # Fast fairness path is valid only if every node has exactly one attribute value.
        seen, ok = 0, True
        for m in self.attr_mask:
            if seen & m:
                ok = False
            seen |= m
        self.single_valued = ok and seen == self.full

    def names(self, mask):
        return frozenset(self.nodes[i] for i in bits(mask))


# --------------------------------------------------------------------------
# 1. Equiconcept / maximal-clique extraction
# --------------------------------------------------------------------------
def _is_equiconcept(I, N):
    """I is an equiconcept if I == f(I), f(S) = common closed neighbours of S."""
    acc = -1
    for v in bits(I):
        acc &= N[v]
        if acc & I != I:            # some pair in I is not adjacent -> not a clique
            return False
    return acc == I                 # nobody outside I is adjacent to all of I




def equiconcepts_clique_generated(ctx):
    """Only build intents generated by cliques (every maximal clique is reachable)."""
    N = ctx.N
    seen = {ctx.full}
    stack = [ctx.full]
    while stack:
        Y = stack.pop()
        for v in bits(Y):
            Z = Y & N[v]
            if Z not in seen:
                seen.add(Z)
                stack.append(Z)
    seen.discard(0)
    return [I for I in seen if _is_equiconcept(I, N)], len(seen)



# --------------------------------------------------------------------------
# 2. Fairness: replaces FairnessFilter + AttributedConceptsDerivation
# --------------------------------------------------------------------------
def fair_subcliques(clique_mask, ctx):
    """All maximal absolute-fair sub-cliques of ONE clique
    (same output as the powerset + cur_maxi loop, without the 2^k blow-up)."""
    groups = [clique_mask & m for m in ctx.attr_mask]
    m = min(popcount(g) for g in groups)
    if m == 0:
        return
    per_group = [list(combinations(list(bits(g)), m)) for g in groups]
    for pick in product(*per_group):
        yield frozenset(ctx.nodes[i] for part in pick for i in part)


def _fair_from_cliques(masks, ctx):
    res = []
    for c in masks:
        res.extend(fair_subcliques(c, ctx))
    return res


# --------------------------------------------------------------------------
# 3. Public entry points (same signatures as before)
# --------------------------------------------------------------------------
def AFCMiner(V, node_attribute_set, R, mode="clique", verbose=True):
    """mode = 'lattice' : build all concepts (paper-faithful)
       mode = 'clique'  : only clique-generated concepts (fastest FCA variant)"""
    ctx = Context(V, node_attribute_set, R)
    build = equiconcepts_clique_generated
    equi, n_concepts = build(ctx)
    res = _fair_from_cliques(equi, ctx)
    if verbose:
        print(f"[AFCMiner/{mode}] concepts built: {n_concepts}, equiconcepts (max cliques): "
              f"{len(equi)}, fair results: {len(res)}")
    return res


